name: Python Package using Conda
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: flexible
    
    - name: Display conda info
      shell: bash -el {0}
      run: |
        conda info
        conda list
    
    - name: Update conda
      shell: bash -el {0}
      run: |
        conda update -n base -c defaults conda
    
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        conda install pytest
        pip install -r requirements.txt || echo "No requirements.txt found"
    
    - name: Build package
      shell: bash -el {0}
      run: |
        mkdir -p build
        echo "Build artifacts" > build/output.txt
        cp -r . build/ || true
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts-${{ matrix.python-version }}
        path: build/
    
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts-${{ matrix.python-version }}
        path: downloaded-artifacts/
