name: Python Package using Conda
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        # Install dependencies from requirements.txt if it exists
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        # Install dependencies from environment.yml if it exists
        if [ -f environment.yml ]; then
          conda env update --file environment.yml --name base
        fi
    
    - name: Lint with flake8
      run: |
        conda install -y flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        conda install -y pytest
        # Only run pytest if there are test files
        if [ -d tests ] || ls test_*.py 1> /dev/null 2>&1; then
          pytest
        else
          echo "No test files found, skipping pytest"
        fi
